# Generated by Django 4.0.2 on 2022-02-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='type',
            field=models.CharField(choices=[('oil', 'oil'), ('grains', 'Grains'), ('Cosmetics', 'Cosmetics')], default='oil', max_length=100),
        ),
    ]
