# Generated by Django 4.0.2 on 2022-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nut', models.CharField(max_length=100)),
                ('price_per_kilo', models.FloatField(default=0)),
                ('dry_fruit', models.CharField(max_length=100)),
                ('price_per_kg', models.FloatField(default=0)),
            ],
        ),
    ]
