# Generated by Django 3.2.4 on 2022-02-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Nuts', 'Nuts')], default='Vegetable', max_length=100)),
                ('VitaminPresent', models.CharField(max_length=100)),
            ],
        ),
    ]
