# Generated by Django 4.0.2 on 2022-02-13 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='form1',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='form1',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
