# Generated by Django 4.0.2 on 2022-02-14 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_alter_form1_age_alter_form1_email_alter_form1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
