# Generated by Django 4.0.2 on 2022-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_form1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
