# Generated by Django 4.0.2 on 2022-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('bus_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Departure_time', models.TimeField()),
                ('Destinations', models.CharField(max_length=50)),
                ('available_seats', models.IntegerField()),
                ('Ticket_cost', models.IntegerField()),
            ],
        ),
    ]
