# Generated by Django 4.0.2 on 2022-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='Destinations',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Bangalore', 'Bangalore')], default='Hyderabad', max_length=50),
        ),
    ]
