# Generated by Django 4.0.2 on 2022-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('text', models.CharField(max_length=264)),
            ],
        ),
    ]
