# Generated by Django 3.2.4 on 2022-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=10)),
                ('departure_time', models.TimeField()),
                ('destination', models.CharField(choices=[('Thanjavur', 'Thanjavur'), ('chennai', 'chennai'), ('Madurai', 'Madurai'), ('Coimbatore', 'Coimbatore'), ('erode', 'erode'), ('ooty', 'ooty'), ('bcm', 'bcm')], default='Thanjavur', max_length=20)),
                ('seats_available', models.IntegerField()),
                ('ticket_cost', models.IntegerField()),
            ],
        ),
    ]
