# Generated by Django 4.0 on 2021-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=10)),
                ('admitted', models.DateField(auto_now_add=True)),
                ('rollno', models.IntegerField()),
            ],
        ),
    ]
