# Generated by Django 4.0 on 2021-12-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_dept_subject_remove_student_admitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='code',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
